//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: service.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Dispatch
import Foundation
import SwiftGRPC
import SwiftProtobuf

internal protocol GamesendCall: ClientCallUnary {}

fileprivate final class GamesendCallBase: ClientCallUnaryBase<Message, Empty>, GamesendCall {
  override class var method: String { return "/Game/send" }
}


/// Instantiate GameServiceClient, then call methods of this protocol to make API calls.
internal protocol GameService: ServiceClient {
  /// Synchronous. Unary.
  func send(_ request: Message, metadata customMetadata: Metadata) throws -> Empty
  /// Asynchronous. Unary.
  @discardableResult
  func send(_ request: Message, metadata customMetadata: Metadata, completion: @escaping (Empty?, CallResult) -> Void) throws -> GamesendCall

}

internal extension GameService {
  /// Synchronous. Unary.
  func send(_ request: Message) throws -> Empty {
    return try self.send(request, metadata: self.metadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  func send(_ request: Message, completion: @escaping (Empty?, CallResult) -> Void) throws -> GamesendCall {
    return try self.send(request, metadata: self.metadata, completion: completion)
  }

}

internal final class GameServiceClient: ServiceClientBase, GameService {
  /// Synchronous. Unary.
  internal func send(_ request: Message, metadata customMetadata: Metadata) throws -> Empty {
    return try GamesendCallBase(channel)
      .run(request: request, metadata: customMetadata)
  }
  /// Asynchronous. Unary.
  @discardableResult
  internal func send(_ request: Message, metadata customMetadata: Metadata, completion: @escaping (Empty?, CallResult) -> Void) throws -> GamesendCall {
    return try GamesendCallBase(channel)
      .start(request: request, metadata: customMetadata, completion: completion)
  }

}

